<?php 
$routeParams = $this->route_params;
if(empty($routeParams) || (is_array($routeParams) && !count($routeParams)))
{
    $routeParams = array();
}
?>

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
of <?php echo $this->totalItemCount; ?>

<!-- First page link -->
<?php if (isset($this->previous)): ?>
	<?php $routeParams['page'] = $this->first?>
  <a href="<?php echo $this->url($this->route, $routeParams); ?>">
    First
  </a> |
<?php else: ?>
  <span class="disabled">First</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
	<?php $routeParams['page'] = $this->previous?>
  <a href="<?php echo $this->url($this->route, array('page' => $routeParams)); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
	<?php $routeParams['page'] = $this->next?>
  <a href="<?php echo $this->url($this->route, $routeParams); ?>">
    Next &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Next &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
	<?php $routeParams['page'] = $this->last?>
  <a href="<?php echo $this->url($this->route, $routeParams); ?>">
    Last
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; ?>

</div>
<?php endif; ?>