<?php 
$routeParams = $this->route_params;
if(empty($routeParams) || (is_array($routeParams) && !count($routeParams)))
{
    $routeParams = array();
}
?>

<?php if ($this->pageCount): ?>

  <span class="text-muted">
      <strong><?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?></strong>
            of
      <strong><?php echo $this->totalItemCount; ?></strong>
  </span>

  <!-- <div class="pagination"> -->
  <div class="btn-group btn-group">    

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
	   <?php $routeParams['page'] = $this->previous?>
      <a class="btn btn-default" href="<?php echo $this->url($this->route, $routeParams); ?>">
        <i class="fa fa-chevron-left"></i>
      </a>
    <?php else: ?>
      <span class="btn btn-default disabled"><i class="fa fa-chevron-left"></i></span>
    <?php endif; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
	   <?php $routeParams['page'] = $this->next?>
      <a class="btn btn-default" href="<?php echo $this->url($this->route, $routeParams); ?>">
        <i class="fa fa-chevron-right"></i>
      </a>
    <?php else: ?>
      <span class="btn btn-default disabled"><i class="fa fa-chevron-right"></i></span>
    <?php endif; ?>
  </div>
<?php endif; ?>