<!-- LOGIN FORM -->
<!--===================================================-->
<div class="cls-content">
	<div class="cls-content-sm panel">
		<div class="panel-body">
			<p class="pad-btm">Sign In to your account</p>
			
			<form action="<?php echo $this->url('zfcuser/login') ?>" method="post" autocomplete="off" >
				
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon"><i class="fa fa-user"></i></div>
						<input type="text" class="form-control" placeholder="Username" name="identity"  >
					</div>
				</div>
				
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
						<input type="password" class="form-control" placeholder="Password" name="credential" >
					</div>
				</div>
				<div class="row">							
					<div class="col-xs-12">
						<div class="form-group text-right">
							<button class="btn btn-success text-uppercase" type="submit">Sign In</button>
						</div>
					</div>
				</div>						
			</form>
		</div>
	</div>
	<div class="pad-ver">
		<a href="<?php echo $this->url('reminder') ?>" class="btn-link mar-rgt">Forgot password ?</a>				
	</div>
</div>
<!--===================================================-->