<?php
$com = $this->communicator();
?>
<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Change Your Password.</h3>
			</div>							
					
			<!--Horizontal Form-->
			<?php $com->printMessage() ?>

			<!--===================================================-->
			<form class="form-horizontal" method="post" action="<?php echo $this->url('users', array('action' => 'change-password'));?>" >
				<div class="panel-body">					
					
					<div class="form-group <?php $com->printErrorClass('password'); ?>">
						<label class="col-sm-3 control-label" for="demo-hor-inputpass">Current Password</label>
						<div class="col-sm-9">
							<input type="password" placeholder="Password" id="demo-hor-inputoldpass" class="form-control" name="password" >	<?php $com->printFieldErrors('password'); ?>
						</div>
					</div>

					<div class="form-group <?php $com->printErrorClass('password'); ?>">
						<label class="col-sm-3 control-label" for="demo-hor-inputpass">New Password</label>
						<div class="col-sm-9">
							<input type="password" placeholder="Password" id="demo-hor-inputpass" class="form-control" name="new_password" >	<?php $com->printFieldErrors('password'); ?>
						</div>
					</div>
					
				</div>
				<div class="panel-footer text-right">
					<button class="btn btn-info" type="submit">Save</button>
				</div>
			</form>

			<!--===================================================-->
			<!--End Horizontal Form-->				
		</div>
	</div>
</div>