<!-- LOGIN FORM -->
<!--===================================================-->
<div class="cls-content">
	<div class="cls-content-sm panel">
		<div class="panel-body">
<p class="pad-btm"><?php echo $this->translate('Sign In to your account'); ?></p>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->form()->openTag($form) ?>
	
	<?php echo $this->formElementErrors($form->get('identity')) ?>   
    
    <div class="form-group">
		<div class="input-group">
			<div class="input-group-addon"><i class="fa fa-user"></i></div>
			<input type="text" class="form-control" placeholder="Username" name="identity"  >
		</div>
	</div>
				
	<div class="form-group">
		<div class="input-group">
			<div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
			<input type="password" class="form-control" placeholder="Password" name="credential" >
		</div>
	</div>
	
	<?php if ($this->redirect): ?>
    	<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
	
	<div class="row">							
		<div class="col-xs-12">
			<div class="form-group text-right">
				<button class="btn btn-success text-uppercase" id="btnSubmit" type="submit">Sign In</button>
			</div>
		</div>
	</div>	

<?php echo $this->form()->closeTag() ?>

		</div>
	</div>

	<!-- 
	<div class="pad-ver">	    
		<a href="" class="btn-link mar-rgt">Forgot password ?</a>				
	</div>
	-->

</div>
<!--===================================================-->